import { useEffect, useState } from 'react'
const DEFAULT_ADMIN = { email:'admin@comwebp.shop', password:'admin123', role:'admin' }
const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:5000'
export default function App(){
  const [theme,setTheme]=useState(()=>localStorage.getItem('cwp_theme')||(window.matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'))
  useEffect(()=>{document.documentElement.setAttribute('data-theme',theme); localStorage.setItem('cwp_theme',theme)},[theme])
  const [mobileMenu,setMobileMenu]=useState(false)
  const [store,setStore]=useState([]); const [local,setLocal]=useState([])
  const [cart,setCart]=useState(()=>JSON.parse(localStorage.getItem('cart')||'[]'))
  const [users,setUsers]=useState(()=>JSON.parse(localStorage.getItem('cwp_users')||'null')||[DEFAULT_ADMIN])
  const [user,setUser]=useState(()=>JSON.parse(localStorage.getItem('cwp_user')||'null'))
  const [orders,setOrders]=useState(()=>JSON.parse(localStorage.getItem('cwp_orders')||'[]'))
  const [showCart,setShowCart]=useState(false); const [showAuth,setShowAuth]=useState(false); const [authMode,setAuthMode]=useState('login')
  const [authForm,setAuthForm]=useState({email:'',password:'',role:'customer'}); const [search,setSearch]=useState(''); const [cat,setCat]=useState('all')
  const [showOrders,setShowOrders]=useState(false); const [editProd,setEditProd]=useState(null)
  const [prodForm,setProdForm]=useState({name:'',price:'',stock:'',description:'',imageUrl:''})
  useEffect(()=>{fetch('https://fakestoreapi.com/products').then(r=>r.json()).then(setStore).catch(()=>{}); fetch(`${API_URL}/api/products`).then(r=>r.json()).then(r=>setLocal(Array.isArray(r)?r:r.data||[])).catch(()=>{})},[])
  useEffect(()=>localStorage.setItem('cart',JSON.stringify(cart)),[cart]); useEffect(()=>localStorage.setItem('cwp_users',JSON.stringify(users)),[users]); useEffect(()=>localStorage.setItem('cwp_orders',JSON.stringify(orders)),[orders])
  const allProducts=[...local.map(p=>({...p,image:p.imageUrl||p.ImageUrl||p.image||`https://picsum.photos/seed/${p.id}/400`,category:'local',isLocal:true})),...store.map(s=>({...s,isLocal:false}))]
  const filtered=allProducts.filter(p=>{const q=search.toLowerCase(); const t=(p.title||p.name||'').toLowerCase(); return (!q||t.includes(q))&&(cat==='all'||p.category===cat)})
  const cats=['all','local',...new Set(store.map(s=>s.category))]
  const login=(e)=>{e.preventDefault(); const f=users.find(u=>u.email===authForm.email&&u.password===authForm.password); if(!f){alert('Wrong email/password');return} setUser(f); localStorage.setItem('cwp_user',JSON.stringify(f)); setShowAuth(false)}
  const register=(e)=>{e.preventDefault(); if(users.find(u=>u.email===authForm.email)){alert('Email exists');return} const n={email:authForm.email,password:authForm.password,role:authForm.role}; setUsers([...users,n]); setUser(n); localStorage.setItem('cwp_user',JSON.stringify(n)); setShowAuth(false)}
  const logout=()=>{setUser(null); localStorage.removeItem('cwp_user'); setShowCart(false); setShowOrders(false)}
  const addToCart=(p)=>{if(!user){setShowAuth(true); setAuthMode('login'); return} setCart(c=>{const ex=c.find(i=>i.id===p.id); if(ex) return c.map(i=>i.id===p.id?{...i,qty:i.qty+1}:i); return [...c,{id:p.id,title:p.title||p.name,price:p.price,image:p.image||p.imageUrl,qty:1}]}); setShowCart(true)}
  const total=cart.reduce((s,i)=>s+i.price*i.qty,0)
  const buy=()=>{if(cart.length===0) return; const o={id:Date.now(),user:user.email,role:user.role,items:cart,total,date:new Date().toLocaleString()}; setOrders([o,...orders]); setCart([]); setShowCart(false); setShowOrders(true)}
  const saveLocalProduct=async(e)=>{e.preventDefault(); if(user?.role!=='admin') return; const payload={name:prodForm.name,description:prodForm.description||prodForm.name,price:parseFloat(prodForm.price),stock:parseInt(prodForm.stock||'10'),imageUrl:prodForm.imageUrl||`https://picsum.photos/seed/${Date.now()}/400`}; try{if(editProd){await fetch(`${API_URL}/api/products/${editProd}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:editProd,...payload})})}else{await fetch(`${API_URL}/api/products`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)})}}catch{} setProdForm({name:'',price:'',stock:'',description:'',imageUrl:''}); setEditProd(null); try{const r=await fetch(`${API_URL}/api/products`).then(r=>r.json()); setLocal(Array.isArray(r)?r:r.data||[])}catch{}}
  const delLocal=async(id)=>{if(!confirm('Delete?')) return; try{await fetch(`${API_URL}/api/products/${id}`,{method:'DELETE'})}catch{}; setLocal(local.filter(l=>l.id!==id))}
  const startEdit=(p)=>{setEditProd(p.id); setProdForm({name:p.name||p.title,price:p.price,stock:p.stock,description:p.description||'',imageUrl:p.imageUrl||p.ImageUrl||p.image||''})}
  const myOrders=user?.role==='admin'?orders:orders.filter(o=>o.user===user?.email)
  return (<div style={{background:'var(--bg)',minHeight:'100vh'}}>
    <div style={{background:'var(--text-h)',color:'var(--bg)',textAlign:'center',padding:'8px',fontSize:'12px'}}>✨ FREE DELIVERY | COD Available ✨</div>
    <div className="header">
      <button onClick={()=>setMobileMenu(!mobileMenu)} className="chip">☰</button>
      <div className="logo">ComWebP<span>.SHOP</span></div>
      <input className="search" placeholder="Search products..." value={search} onChange={e=>setSearch(e.target.value)} />
      <button onClick={()=>setTheme(theme==='dark'?'light':'dark')} className="chip">{theme==='dark'?'☀️':'🌙'}</button>
      {user? <><span className="chip">{user.role} • {user.email.slice(0,15)}</span><button className="chip" onClick={()=>setShowOrders(true)}>Orders {myOrders.length}</button><button className="add" style={{maxWidth:'80px'}} onClick={()=>setShowCart(true)}>🛒 {cart.reduce((a,b)=>a+b.qty,0)}</button><button className="chip" onClick={logout}>Logout</button></> : <><button className="chip" onClick={()=>{setShowAuth(true); setAuthMode('login')}}>Login</button><button className="add" style={{maxWidth:'100px'}} onClick={()=>{setShowAuth(true); setAuthMode('register')}}>Register</button></>}
    </div>
    {mobileMenu && <div style={{padding:'10px 16px',borderBottom:'1px solid var(--border)',display:'flex',gap:'8px',overflowX:'auto'}}>{cats.map(c=><button key={c} className={`chip ${cat===c?'active':''}`} onClick={()=>{setCat(c); setMobileMenu(false)}}>{c}</button>)}</div>}
    {user?.role==='admin' && <div className="admin"><h3 style={{margin:0,color:'var(--text-h)'}}>🛠 Admin - {local.length} Local</h3><form onSubmit={saveLocalProduct} style={{display:'flex',gap:'8px',flexWrap:'wrap',marginTop:'10px'}}><input required placeholder="Name" value={prodForm.name} onChange={e=>setProdForm({...prodForm,name:e.target.value})} style={{flex:'1'}}/><input required placeholder="Price" type="number" step="0.01" value={prodForm.price} onChange={e=>setProdForm({...prodForm,price:e.target.value})} style={{width:'90px'}}/><input required placeholder="Stock" type="number" value={prodForm.stock} onChange={e=>setProdForm({...prodForm,stock:e.target.value})} style={{width:'70px'}}/><input placeholder="Image URL" value={prodForm.imageUrl} onChange={e=>setProdForm({...prodForm,imageUrl:e.target.value})} style={{flex:'1'}}/><button className="add" style={{width:'80px'}}>{editProd?'Update':'Add'}</button></form></div>}
    <div style={{padding:'10px 16px',display:'flex',gap:'8px',overflowX:'auto'}}>{cats.map(c=><button key={c} className={`chip ${cat===c?'active':''}`} onClick={()=>setCat(c)}>{c}</button>)}</div>
    <div className="grid">{filtered.map((p,i)=><div key={i} className="card"><img src={p.image} alt="" onError={e=>e.currentTarget.src=`https://picsum.photos/seed/${p.id}/400`} /><h4>{p.title||p.name}</h4><div className="price">${p.price}</div><div style={{display:'flex',gap:'6px',marginTop:'8px'}}><button className="add" onClick={()=>addToCart(p)}>Add to Cart</button>{user?.role==='admin'&&p.isLocal&&<><button className="chip" onClick={()=>startEdit(p)}>Edit</button><button className="chip" onClick={()=>delLocal(p.id)}>Del</button></>}</div></div>)}</div>
    {(showCart||showOrders)&&<div className="overlay" onClick={()=>{setShowCart(false); setShowOrders(false)}}></div>}
    <div className={`cart-drawer ${showCart?'open':''}`}><h3 style={{color:'var(--text-h)',margin:0}}>Cart</h3><div style={{flex:1,overflow:'auto'}}>{cart.map(it=><div key={it.id} style={{display:'flex',justifyContent:'space-between',borderBottom:'1px solid var(--border)',padding:'6px 0'}}><span>{it.title.slice(0,25)} x{it.qty}</span><button className="chip" onClick={()=>setCart(c=>c.filter(x=>x.id!==it.id))}>X</button></div>)}</div><b style={{color:'var(--text-h)'}}>Total ${total.toFixed(2)}</b><button className="add" onClick={buy}>Buy</button><button className="chip" onClick={()=>setShowCart(false)}>Close</button></div>
    {showOrders&&<div className="modal-bg" onClick={()=>setShowOrders(false)}><div className="modal" onClick={e=>e.stopPropagation()}><h3 style={{color:'var(--text-h)'}}>Orders</h3>{myOrders.map(o=><div key={o.id} style={{border:'1px solid var(--border)',padding:'8px',borderRadius:'8px',marginBottom:'6px',background:'var(--code-bg)'}}><div style={{fontSize:'12px'}}>{o.date} - ${o.total.toFixed(2)} - {o.user}</div></div>)}<button className="chip" onClick={()=>setShowOrders(false)}>Close</button></div></div>}
    {showAuth&&<div className="modal-bg" onClick={()=>setShowAuth(false)}><div className="modal" onClick={e=>e.stopPropagation()}><h3 style={{color:'var(--text-h)',textTransform:'capitalize'}}>{authMode}</h3><form onSubmit={authMode==='login'?login:register} style={{display:'flex',flexDirection:'column',gap:'8px'}}><input required type="email" placeholder="Email" value={authForm.email} onChange={e=>setAuthForm({...authForm,email:e.target.value})} /><input required type="password" placeholder="Password" value={authForm.password} onChange={e=>setAuthForm({...authForm,password:e.target.value})} />{authMode==='register'&&<div style={{display:'flex',gap:'8px'}}><button type="button" className={`chip ${authForm.role==='customer'?'active':''}`} onClick={()=>setAuthForm({...authForm,role:'customer'})}>Customer</button><button type="button" className={`chip ${authForm.role==='admin'?'active':''}`} onClick={()=>setAuthForm({...authForm,role:'admin'})}>Admin</button></div>}<button className="add" type="submit">{authMode}</button></form></div></div>}
  </div>)
}